name: doctor_booking
description: Medical Booking App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Required for task
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.5.1

  # Keep minimal UI deps
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

